### PR TITLE
Fixes/hydraitems

### PR DESCRIPTION
**Pull request by Marsunpaisti**
Not sure how to do this since git doesnt understand .w3x files. **This .w3x has the fixes/mapfixes changes** in addition to hydraac fins being fixed to +4 armor and added spellshield in tooltip, removed agile feet ability which didnt work in the first place ( #118 ). 
Hydra claws also had the hydraac fins +18 armor ability without saying that in the description. Removed that aswell.

### CODE REVIEW

**Comment by jonathanmclaus** [comment]
Unfortunately, GitHub doesn't handle binary files very well. This is part of why we're trying to transition to Wurst for object editing. Currently, just post in #developers that you are working on the map and hopefully no one else will work on it at the same time.

I would prefer renaming Hydraac Fins to Hydra Fins, as I don't think Hydraac is actually a word.

**Comment by jonathanmclaus** [comment]
Does this duplicate any work in #128 ?

**Comment by Marsunpaisti** [comment]
> 
> 
> Does this duplicate any work in #128 ?

To be honest I had no idea if the pull request also updates any commits I made after the request so I made a new one after making a small adjustment.

**Comment by jonathanmclaus** [comment]
It does. You'll notice the commit logs for #127, #128, and #129 share
entries.

**Pull request closed without merging**
