### PR TITLE
Mage masher nerf

### PR DESCRIPTION
**Pull request by totony-misc**
having played a lot on the new patch, 10 mana burn is too much

### CODE REVIEW

**Comment by jonathanmclaus** [comment]
Can you make the tooltip for Mage Masher reference this value (and also fix the other incorrect parts)?

**Comment by jonathanmclaus** [comment]
Also I don't think this really fixes the issue for team games, so changes introducing a scaling value for stacking (similar to spears) would be welcome.

**Comment by totony-misc** [comment]
> Also I don't think this really fixes the issue for team games, so changes introducing a scaling value for stacking (similar to spears) would be welcome.

im not sure people actually want that but im not planning on working too much on itt right now

**Comment by theQuazz** [comment]
Scaling it as I suggested would be better

**Comment by jonathanmclaus** [comment]
Your way doesn't scale based on players either though.

**Comment by theQuazz** [comment]
No, I just don't think that it's an issue that should be solved for. You should have to have great position management as a caster. Implementing a solution similar to spears more broadly would be a shame in my opinion because I see the spears change as a shim rather than a long term change.

**Comment by jonathanmclaus** [comment]
Can't really call the spears change a shim when it's been there for 3
years. I think people are familiar enough with the system that it would
work for mana burn.

**Comment by theQuazz** [comment]
I'd still call it a shim. My goal has been to introduce more items which increase your hp pool thus making spears ineffective. But progress on that has been delayed for various reasons, primarily lack of consensus. Hence why we've been stuck with this shim. That doesn't make it not a shim.

**Comment by totony-misc** [comment]
> Scaling it as I suggested would be better

what did you suggest? % of mana burn?

**Comment by theQuazz** [comment]
% of current mana with a minimum value

**Comment by jonathanmclaus** [comment]
Conflicts with #750. Will open a new PR if needed.

**Pull request closed without merging**
