### PR TITLE
[Edit] Current Beta version

### PR DESCRIPTION
**Pull request by Jaccouille**
I wurstified ALL mages spells, cleaned existing spells.
This is just to show off, I only tested spells for elementalist, I'll merge the other branch currently in PR into this one then test all spells. I copy pasted the Abilities definition, there shouldn't be much problem.

I wrapped it up in classes so we can create other spells easily, like just modifying hotkey & buttonPosition,
no more trouble with positioning spells & hotkey, just make another instance with a different hotkey

### CODE REVIEW

**Comment by Jaccouille** [comment]
Just note that I had to merge previous branch currently in Pull request (TrollUnitFactory, didn't push new code yet) to test the spell, would like to merge this one after the others. Currently wurstifying priest spells.

**Comment by Jaccouille** [comment]
So hum I wurstified every troll spells except sniff, camoflage and priest magic mist still cast the jurst battle mist (was lazy).

**Comment by Jaccouille** [comment]
url
I don't understand this

**Comment by theQuazz** [comment]
cc @Frotty

**Comment by Frotty** [comment]
There is no (wurst) error. Idk about circleCI, does "received killed command" mean that the command exited with non-zero status? Did you try simply restarting the build?
Does the master build if you retry?

**Comment by theQuazz** [comment]
@Frotty maybe it didn't exit cleanly

**Comment by Frotty** [comment]
Files changed: 149

😅

**Comment by Jaccouille** [comment]
Got to admit, this hurts my eyes

**Comment by Frotty** [comment]
fix build pls

**Comment by jonathanmclaus** [comment]
@Frotty What do you think the problem is? The map compiles locally and only fails when running from Circle CI. The ability ID isn't referenced in either the base `build1.w3x` or manually used in any object definitions. If there is a conflict, it seems like it would be from multiple calls to `ABIL_ID_GEN.next()`.

**Pull request merged**
