### PR TITLE
Added workaround for spellbook failure on inventory move.

### PR DESCRIPTION
**Pull request by jonathanmclaus**

### CODE REVIEW

**Comment by jonathanmclaus** [comment]
This should be viewed with whitespace off because I changed line endings.

**Comment by jonathanmclaus** [comment]
Fixes #349

**Comment by Jaccouille** [comment]
Why are the files fully highlighted when I look for diff on the github interface? [Files Changed](https://github.com/island-troll-tribes/island-troll-tribes/pull/358/files)

**Comment by HallerJohn** [comment]
He might have copy pasted the file. Github treats that as, you deleted the whole page then added all of this new stuff

**Comment by jonathanmclaus** [comment]
I touched the file in VS Code, which automatically changed all the line endings to the right ones. Like I said, view it without considering the whitespace in the diff.

**Comment by jonathanmclaus** [comment]
Issue is that moving a spellbook in your inventory breaks it - you can't use the abilities and it can lock you inside the spellbook without you realizing. This reduces the problems associated with that by automatically replacing the spellbook in your inventory if you move it.

**Pull request merged**
