### PR TITLE
Reduced health for Tent.

### PR DESCRIPTION
**Pull request by Jaccouille**
$changelog: Reduced health for Tent from 160 to 100.

Tent is pretty cheap, I believe its hp should be adjusted in relation to its cost.

### CODE REVIEW

**Comment by jonathanmclaus** [comment]
I was thinking something more like 40 - you can't kill it without wasting time in a rush but not feasible after the enemy has axes. Do you think that's too low?

**Comment by jonathanmclaus** [comment]
I don't think we should let it be pack. Let's try reducing the HP to 100 for now and see if it's still abusable.

**Review by jonathanmclaus — CHANGES_REQUESTED** [review]
Revert the change for abilities.

**Comment by Jaccouille** [comment]
And change its armor type from fortified to large? Fortified reduces hero damage by 50%, if you have 20 damage, it would take you 10 hits to kill a tent.

**Pull request merged**
