### PR TITLE
Fixed multiboard bug caused by an observer leaving.

### PR DESCRIPTION
**Pull request by HallerJohn**
*Fix bug with scoreboard caused by obs leaving game.

### CODE REVIEW

**Comment by Jaccouille** [comment]
Scoreboard? Isn't it a bug rather related to Tribeboard? Can you describe it? Is it related to #352? Did you test the fix?
You can test by opening 3 warcraft 3 client, create a LAN game, join it with all the client, start it, put 1 client in observer mode at the start of the game, then test the fix.

**Comment by jonathanmclaus** [comment]
I think the terms scoreboard and multiboard are being conflated. This is referring to the board used to display the statistics for each member of your tribe, i.e. health, energy, and heat.

**Comment by HallerJohn** [comment]
Yeah that was my mistake I mean the tribe board. The bug was that it would print an error message if an obs left the game. And yes me and mt tested it and it worked fine.

**Comment by jonathanmclaus** [comment]
We didn't test if this fixes the issue in #352 but I doubt it's related.

**Pull request merged**
